### PR TITLE
fix(eslint-plugin): eslint rules not found

### LINKED ISSUE #225: eslint-plugin broken from 0.18.1
In an nx monorepo with `eslint@9.32.0`, and the following `eslint.config.mjs` file:

```js
import nx from '@nx/eslint-plugin';
import sheriff from '@softarc/eslint-plugin-sheriff';

export default [
  sheriff.configs.all,
  // ...everything else as nx provides it out of the box
];
```

And with the following `sheriff.config.ts` file:

```typescript
import { SheriffConfig } from '@softarc/sheriff-core';

export const config: SheriffConfig = {
  enableBarrelLess: true,
  modules: {
    'apps/whatever/src': 'app',
    'libs/foo/src': 'foo',
    'libs/bar/src': 'bar',
  },
  depRules: {
    'root': 'noTag',
    'noTag': 'noTag',
    'app': ['foo', 'bar'],
    'foo': ['foo'],
    'bar': ['bar'],
  },
};
```

When my lib under `libs/bar/src` contains an import from `foo` (which is not allowed according to the depRules above), then I would expect a lint error.

This worked as expected with the version `0.18.0` but after updating to `0.19.0` it no longer errors.

Working backwards, it looks like it first broke in version `0.18.1`.

Also, any `// eslint-disable-next-line @softarc/sheriff/dependency-rule` comments now cause the following error when linting:

```
error  Definition for rule '@softarc/sheriff/dependency-rule' was not found  @softarc/sheriff/dependency-rule
```

### PR DESCRIPTION
**Pull request by michaelbe812**
From what I have seen the issue #225 is caused by an incorrect file pattern which was introduced in commit #837d792

Fixes #225

### CODE REVIEW

File: packages/eslint-plugin/src/lib/configs/all.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import type { TSESLint } from '@typescript-eslint/utils';
 import rules from '../rules';
 
 const commonConfig: TSESLint.FlatConfig.Config = {
-  files: ['*.ts, *.js'],
```
Comment (weberhofer) [inline packages/eslint-plugin/src/lib/configs/all.ts:5]: Unbelieveable: I have checked that line before but didn't see the issue.
Following my tests, the line must be like that:
```js
files: ['**/*.ts', '**/*.js'],

Comment (michaelbe812) [reply packages/eslint-plugin/src/lib/configs/all.ts:5]: Oh yes, you're right. I will update my PR :)

**Comment by michaelbe812** [comment]
> @weberhofer @michaelbe812, Thanks again. I am currently on holiday and have therefore limited availability (I can still publish the lib).
> 
> My primary concern is the following: We have so many integration tests, but why did none of them fail? If our tests failed this case completely, we should probably also add one.

This is also what I am wondering about. Somehow I have the feeling that something's wrong with the integration tests. I'll try to check

**Comment by weberhofer** [comment]
I think the old file definitions worked on older eslint versions. My configurations broke after eslint 9.30.1. Integration tests seem to use eslint 8.x versions.

**Comment by michaelbe812** [comment]
> @michaelbe812, I'd like to push two new integration tests to your branch. One will run `nx-create-workspace` and apply our eslint rules via a simple script. The other one does the same for the Angular CLI. In that way, we would be notified if nx or `angular-eslint/schematics` changes their layout.

Great idea 💡 this will definitely add some more safety nets. 

I'm just asking myself if it would not be enough to just scaffold minimal projects with each eslint version which should be supported instead of full-blown nx and angular workspaces?

**Comment by rainerhahnekamp** [comment]
Since I haven't been able to come up with the integration tests and we have a blocker here, I merged the fix and published.

Integration tests will be done in a separate, follow-up issue.

Thanks @michaelbe812 and @weberhofer for fixing this.
